---

- name: Ensure that the application file permissions are set properly
  file: path={{ virtualenv_path }}
        recurse=yes
        owner={{ uwsgi_user }}
        group={{ uwsgi_group }}
        state=directory
  changed_when: false
