---

- name: Install packages required by the Django app inside virtualenv
  pip: virtualenv={{ virtualenv_path }} requirements={{ requirements_file }}

- name: Run the Django makemigration command
  django_manage:
    command: makemigration
    app_path: "{{ project_path }}"
    virtualenv: "{{ virtualenv_path }}"
    settings: "{{ django_settings_file }}"
  when: run_django_makemigration is defined and run_django_makemigration
  tags: django.makemigration

- name: Run Django database migrations
  django_manage:
    command: migrate
    app_path: "{{ project_path }}"
    virtualenv: "{{ virtualenv_path }}"
    settings: "{{ django_settings_file }}"
  # when: run_django_db_migrations is defined and run_django_db_migrations
  tags: django.migrate

- name: Run Django collectstatic
  django_manage:
    command: collectstatic
    app_path: "{{ project_path }}"
    virtualenv: "{{ virtualenv_path }}"
    settings: "{{ django_settings_file }}"
  # when: run_django_collectstatic is defined and run_django_collectstatic
  # notify: restart application
  tags: django.collectstatic

#- name: Create Django Superuser
#  django_manage:
#    command: createsuperuser
#    app_path: "{{ project_path }}"
#    virtualenv: "{{ virtualenv_path }}"
#    settings: "{{ django_settings_file }}"
#  # when: run_django_db_migrations is defined and run_django_db_migrations
#  tags: django.migrate
#
#- name: Check if Super User exists?
#  command: echo "from django.contrib.auth import get_user_model; User = get_user_model(); print(User.objects.filter(username='{{application_name}}').count()>0)" | {{ virtualenv_path }}/bin/python3 {{ project_path }}/manage.py shell
#  args:
#    chdir: "{{ project_path }}"
#  environment:
#    DJANGO_SETTINGS_MODULE: "{{ django_settings_file }}"
#  register: superuser_existed
#- name: Create super user
#  django_manage: command="createsuperuser --noinput --username={{application_name}} --email={{admin_email}}"
#                 app_path={{django_dir}}
#                 virtualenv={{django_dir}}/venv
#                 settings={{settings}}
#  when: not superuser_existed