---

# Virtualenv settings.
enable_deadsnakes_ppa: false
recreate_virtualenv: false
virtualenv_python_version: "{{ base_python_package }}"


#app_path: "{{ project_path}}/{{ application_name }}"

requirements_file: "{{ project_path }}/requirements.txt"

# Domain Configurations
domain_name: peddlesoft.com

# Git settings
git_url: "PVMT-CO/pavement-head.git"
git_branch: main



# UWSGI settings.
uwsgi_user: "{{ lookup('env', 'USER') | application_name }}"
uwsgi_group: www-data


# Nginx settings.
nginx_static_dir: "{{ project_path }}/static/"
nginx_media_dir: "{{ project_path }}/media/"


# Django environment variables.
django_environment:
  DJANGO_SETTINGS_MODULE: "{{ django_settings_file }}"
  DJANGO_SECRET_KEY: "{{ django_secret_key }}"
  MEDIA_ROOT: "{{ nginx_media_dir }}"
  STATIC_ROOT: "{{ nginx_static_dir }}"
  DATABASE_NAME: "{{ db_name }}"
  DATABASE_USER: "{{ db_user }}"
  DATABASE_PASSWORD: "{{ db_password }}"
  BROKER_URL: "{{ broker_url }}"
